# Generated by Django 3.0.3 on 2020-02-12 16:46

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Excursion',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('detailPageName', models.CharField(max_length=400)),
                ('portID', models.CharField(max_length=10)),
                ('types', models.CharField(max_length=10)),
                ('topology', django_mysql.models.ListCharField(models.CharField(max_length=10), max_length=66, size=6)),
                ('activityLevel', models.CharField(max_length=20)),
                ('collectionType', models.CharField(max_length=30)),
                ('duration', models.CharField(max_length=100)),
                ('language', django_mysql.models.ListCharField(models.CharField(max_length=10), max_length=66, size=6)),
                ('priceLevel', models.IntegerField()),
                ('currency', models.CharField(max_length=10)),
                ('mealInfo', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], default='active', max_length=10)),
                ('shortDescription', models.CharField(blank=True, max_length=200)),
                ('longDescription', models.TextField()),
                ('externalContent', models.BooleanField(default=False)),
                ('minimumAge', models.CharField(blank=True, max_length=10)),
                ('wheelChairAccecsible', models.BooleanField(default=False)),
                ('featured', models.BooleanField(default=True)),
            ],
        ),
    ]
